version: "2"
linters:
  enable:
    - misspell
    - revive
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - revive
        path: _test\.go
      - linters:
          - misspell
          - revive
        path: gen_.*\.go
      - linters:
          - errcheck
          - revive
        path: examples/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
