package cli

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/amrshadid/go-dicom/tag"
)

// CodifyCommand generates Go code to recreate a DICOM file.
type CodifyCommand struct {
	filename       string
	outputFile     string
	excludeSize    int
	excludePrivate bool
	packageName    string
	functionName   string
	help           bool
}

// NewCodifyCommand creates a new codify command.
func NewCodifyCommand() *CodifyCommand {
	return &CodifyCommand{
		packageName:  "main",
		functionName: "createDataset",
		excludeSize:  100,
	}
}

// Name returns the command name.
func (cc *CodifyCommand) Name() string {
	return "codify"
}

// Description returns the command description.
func (cc *CodifyCommand) Description() string {
	return "Read a DICOM file and produce Go code to create it"
}

// AddFlags adds command flags to the flag set.
func (cc *CodifyCommand) AddFlags(fs *flag.FlagSet) {
	fs.BoolVar(&cc.help, "h", false, "Show help for this command")
	fs.BoolVar(&cc.help, "help", false, "Show help for this command")
	fs.IntVar(&cc.excludeSize, "exclude-size", 100, "Exclude binary data larger than this size (bytes)")
	fs.BoolVar(&cc.excludePrivate, "exclude-private", true, "Exclude private tags")
	fs.StringVar(&cc.outputFile, "output", "", "Output file (if empty, write to stdout)")
	fs.StringVar(&cc.packageName, "package", "main", "Go package name")
	fs.StringVar(&cc.functionName, "function", "createDataset", "Function name")
}

// Execute runs the codify command.
func (cc *CodifyCommand) Execute(args []string) error {
	fs := flag.NewFlagSet(cc.Name(), flag.ContinueOnError)
	cc.AddFlags(fs)

	positional, err := ParseArgs(fs, args)
	if err != nil {
		return fmt.Errorf("codify: failed to parse flags: %v", err)
	}

	// Check if help flag was set
	if cc.help {
		cc.showHelp()
		return nil
	}

	remaining := positional
	if len(remaining) == 0 {
		return fmt.Errorf("codify: missing file specification\nRun 'go-dicom codify -h' for usage")
	}

	cc.filename = remaining[0]

	if _, err := os.Stat(cc.filename); os.IsNotExist(err) {
		return fmt.Errorf("codify: file not found: %s", cc.filename)
	}

	elements, err := readDICOMFile(cc.filename)
	if err != nil {
		return fmt.Errorf("codify: failed to read DICOM file: %v", err)
	}

	code := cc.generateCode(elements)

	if cc.outputFile != "" {
		if err := os.WriteFile(cc.outputFile, []byte(code), 0644); err != nil {
			return fmt.Errorf("codify: failed to write output file: %v", err)
		}
		fmt.Printf("Code written to: %s\n", cc.outputFile)
	} else {
		fmt.Println(code)
	}

	return nil
}

// generateCode generates Go code from DICOM elements
func (cc *CodifyCommand) generateCode(elements []DicomElement) string {
	var code strings.Builder

	fmt.Fprintf(&code, "package %s\n\n", cc.packageName)

	// A package main needs a main function, or it does not build:
	//
	//	runtime.main_main·f: function main is undeclared in the main package
	//
	// This generated `package main` with the dataset builder and nothing to call it,
	// so the default output of a command whose whole purpose is to emit runnable Go
	// could not be compiled or run. The extra import is only pulled in where the
	// generated main uses it.
	isProgram := cc.packageName == "main"

	code.WriteString("import (\n")
	if isProgram {
		code.WriteString("\t\"fmt\"\n\n")
	}
	code.WriteString("\t\"github.com/amrshadid/go-dicom/dataset\"\n")
	code.WriteString("\t\"github.com/amrshadid/go-dicom/dataelem\"\n")
	code.WriteString("\t\"github.com/amrshadid/go-dicom/tag\"\n")
	code.WriteString(")\n\n")

	fmt.Fprintf(&code, "// %s creates a DICOM dataset from a file\n", cc.functionName)
	code.WriteString("// Auto-generated by: go-dicom codify\n")
	fmt.Fprintf(&code, "func %s() *dataset.Dataset {\n", cc.functionName)
	code.WriteString("\tds := dataset.NewDataset()\n\n")

	elementCount := 0
	for _, elem := range elements {
		if cc.excludePrivate && isPrivateTag(elem.Tag) {
			continue
		}

		if len(elem.Value) > cc.excludeSize {
			fmt.Fprintf(&code, "\t// TODO: %s (%s) - Binary data excluded (%d bytes)\n",
				elem.Tag, elem.VR, len(elem.Value))
			continue
		}

		elementCode := cc.generateElementCode(elem)
		if elementCode != "" {
			code.WriteString(elementCode)
			elementCount++
		}
	}

	code.WriteString("\n\treturn ds\n")
	code.WriteString("}\n")

	if elementCount > 0 {
		fmt.Fprintf(&code, "\n// Total elements: %d\n", elementCount)
	}

	// The entry point, so `go run` on the output does something and the file
	// compiles as the program its package clause claims it is.
	if isProgram {
		fmt.Fprintf(&code, `
func main() {
	ds := %s()
	fmt.Printf("built a data set with %%d elements\n", ds.Length())
}
`, cc.functionName)
	}

	return code.String()
}

// generateElementCode generates Go code for a single element
func (cc *CodifyCommand) generateElementCode(elem DicomElement) string {
	var code strings.Builder

	parts := strings.Split(elem.Tag, ",")
	if len(parts) != 2 {
		return ""
	}

	var group, element uint16
	_, err := fmt.Sscanf(parts[0], "%X", &group)
	if err != nil {
		return ""
	}
	_, err = fmt.Sscanf(parts[1], "%X", &element)
	if err != nil {
		return ""
	}

	t := tag.New(group, element)
	tagName := t.GetName()
	if tagName == "" {
		tagName = fmt.Sprintf("Tag_%04X_%04X", group, element)
	}

	valueCode := cc.formatValue(elem.VR, elem.Value)
	if valueCode == "" {
		return ""
	}

	fmt.Fprintf(&code, "\t// (%s) %s (%s)\n", elem.Tag, tagName, elem.VR)
	code.WriteString("\tds.Add(dataelem.NewDataElement(\n")
	fmt.Fprintf(&code, "\t\ttag.New(0x%04X, 0x%04X),\n", group, element)
	fmt.Fprintf(&code, "\t\tdataelem.%s,\n", elem.VR)
	fmt.Fprintf(&code, "\t\t%s,\n", valueCode)
	code.WriteString("\t))\n\n")

	return code.String()
}

// textVRs are the value representations whose bytes are text. Everything else is
// binary, however short, and must not be rendered as a Go string.
var textVRs = map[string]bool{
	"AE": true, "AS": true, "CS": true, "DA": true, "DS": true, "DT": true,
	"IS": true, "LO": true, "LT": true, "PN": true, "SH": true, "ST": true,
	"TM": true, "UC": true, "UI": true, "UR": true, "UT": true,
}

// formatValue renders a value as Go source.
//
// The previous version produced source that would not compile, and dropped data:
//
//   - It decided a value was printable with `for _, r := range string(value)`.
//     Ranging a string yields U+FFFD for each byte that is not valid UTF-8, and
//     U+FFFD is not less than 32 — so arbitrary binary passed the printable test and
//     was written into the source raw. A four-byte group-length UL became
//     `"\x86..."` unescaped, and the generated file failed to parse with "illegal
//     UTF-8 encoding". Whether it happened depended on the file: an all-ASCII data
//     set generated fine, which is why it went unnoticed.
//
//   - Escaping was four hand-written ReplaceAll calls, so every control character
//     other than tab, newline and carriage return went through untouched.
//
//   - Numeric VRs — US, UL, SS, SL, FL, FD, AT — are binary, and were treated as
//     text. Where that did not break the source it produced a string where the
//     reader expects a number.
//
// Now: text VRs go through strconv.Quote, which escapes everything and always emits
// valid UTF-8 source. Everything else is emitted as the bytes it is, so the generated
// data set actually matches the file rather than carrying a placeholder comment where
// a value should be.
func (cc *CodifyCommand) formatValue(vr string, value []byte) string {
	vr = strings.TrimSpace(vr)

	if textVRs[vr] {
		text := strings.TrimRight(string(value), "\x00")

		// Invalid UTF-8 in a text VR means the value is not what its VR claims —
		// mislabelled, or a character set this is not decoding. Emit the bytes rather
		// than a string that would misrepresent them or break the source.
		if utf8.ValidString(text) {
			return strconv.Quote(text)
		}
		return byteLiteral(value, cc.excludeSize)
	}

	return byteLiteral(value, cc.excludeSize)
}

// byteLiteral renders bytes as a Go []byte literal, or as a comment when there are
// more than the caller wants inlined.
//
// The size limit is what -exclude-size is for: pixel data as a literal would be
// megabytes of source. Below it the real bytes are written, so the generated code
// reproduces the value instead of describing it.
func byteLiteral(value []byte, limit int) string {
	if limit > 0 && len(value) > limit {
		return fmt.Sprintf("[]byte{/* %d bytes, exceeds -exclude-size */}", len(value))
	}
	if len(value) == 0 {
		return "[]byte{}"
	}

	var b strings.Builder
	b.WriteString("[]byte{")
	for i, v := range value {
		if i > 0 {
			b.WriteString(", ")
		}
		// Wrapped, because a long single line of hex is unreadable and gofmt will not
		// break it for us.
		if i > 0 && i%12 == 0 {
			b.WriteString("\n\t\t\t")
		}
		fmt.Fprintf(&b, "0x%02X", v)
	}
	b.WriteString("}")
	return b.String()
}

// showHelp displays help information for the codify command.
func (cc *CodifyCommand) showHelp() {
	fmt.Print(`COMMAND: codify - Convert DICOM file to Go code

USAGE:
  go-dicom codify <file> [options]

DESCRIPTION:
  Read a DICOM file and produce Go code that can recreate it. Useful for
  documentation, testing, and sharing DICOM file structures.

OPTIONS:
  -h, --help                Show help for this command
  --exclude-size <N>        Exclude binary data larger than N bytes (default: 100)
  --exclude-private         Exclude private tags (default: true)
  --output <file>           Output file (if not specified, writes to stdout)
  --package <name>          Go package name (default: main)
  --function <name>         Function name (default: createDataset)

EXAMPLES:
  go-dicom codify patient.dcm
  go-dicom codify patient.dcm > create_patient.go
  go-dicom codify patient.dcm --output patient.go --exclude-size 1000
  go-dicom codify patient.dcm --exclude-private=false
  go-dicom codify patient.dcm --package mypackage --function createMyDataset
  go-dicom codify -h
`)
}
