package cli

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/amrshadid/go-dicom/tag"
)

// CodifyCommand generates Go code to recreate a DICOM file.
type CodifyCommand struct {
	filename       string
	outputFile     string
	excludeSize    int
	excludePrivate bool
	packageName    string
	functionName   string
	help           bool
}

// NewCodifyCommand creates a new codify command.
func NewCodifyCommand() *CodifyCommand {
	return &CodifyCommand{
		packageName:  "main",
		functionName: "createDataset",
		excludeSize:  100,
	}
}

// Name returns the command name.
func (cc *CodifyCommand) Name() string {
	return "codify"
}

// Description returns the command description.
func (cc *CodifyCommand) Description() string {
	return "Read a DICOM file and produce Go code to create it"
}

// AddFlags adds command flags to the flag set.
func (cc *CodifyCommand) AddFlags(fs *flag.FlagSet) {
	fs.BoolVar(&cc.help, "h", false, "Show help for this command")
	fs.BoolVar(&cc.help, "help", false, "Show help for this command")
	fs.IntVar(&cc.excludeSize, "exclude-size", 100, "Exclude binary data larger than this size (bytes)")
	fs.BoolVar(&cc.excludePrivate, "exclude-private", true, "Exclude private tags")
	fs.StringVar(&cc.outputFile, "output", "", "Output file (if empty, write to stdout)")
	fs.StringVar(&cc.packageName, "package", "main", "Go package name")
	fs.StringVar(&cc.functionName, "function", "createDataset", "Function name")
}

// Execute runs the codify command.
func (cc *CodifyCommand) Execute(args []string) error {
	fs := flag.NewFlagSet(cc.Name(), flag.ContinueOnError)
	cc.AddFlags(fs)

	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("codify: failed to parse flags: %v", err)
	}

	// Check if help flag was set
	if cc.help {
		cc.showHelp()
		return nil
	}

	remaining := fs.Args()
	if len(remaining) == 0 {
		return fmt.Errorf("codify: missing file specification\nRun 'go-dicom codify -h' for usage")
	}

	cc.filename = remaining[0]

	if _, err := os.Stat(cc.filename); os.IsNotExist(err) {
		return fmt.Errorf("codify: file not found: %s", cc.filename)
	}

	elements, err := readDICOMFile(cc.filename)
	if err != nil {
		return fmt.Errorf("codify: failed to read DICOM file: %v", err)
	}

	code := cc.generateCode(elements)

	if cc.outputFile != "" {
		if err := os.WriteFile(cc.outputFile, []byte(code), 0644); err != nil {
			return fmt.Errorf("codify: failed to write output file: %v", err)
		}
		fmt.Printf("Code written to: %s\n", cc.outputFile)
	} else {
		fmt.Println(code)
	}

	return nil
}

// generateCode generates Go code from DICOM elements
func (cc *CodifyCommand) generateCode(elements []DicomElement) string {
	var code strings.Builder

	fmt.Fprintf(&code, "package %s\n\n", cc.packageName)
	code.WriteString("import (\n")
	code.WriteString("\t\"github.com/amrshadid/go-dicom/dataset\"\n")
	code.WriteString("\t\"github.com/amrshadid/go-dicom/dataelem\"\n")
	code.WriteString("\t\"github.com/amrshadid/go-dicom/tag\"\n")
	code.WriteString(")\n\n")

	fmt.Fprintf(&code, "// %s creates a DICOM dataset from a file\n", cc.functionName)
	code.WriteString("// Auto-generated by: dicom-cli codify\n")
	fmt.Fprintf(&code, "func %s() *dataset.Dataset {\n", cc.functionName)
	code.WriteString("\tds := dataset.NewDataset()\n\n")

	elementCount := 0
	for _, elem := range elements {
		if cc.excludePrivate && isPrivateTag(elem.Tag) {
			continue
		}

		if len(elem.Value) > cc.excludeSize {
			fmt.Fprintf(&code, "\t// TODO: %s (%s) - Binary data excluded (%d bytes)\n",
				elem.Tag, elem.VR, len(elem.Value))
			continue
		}

		elementCode := cc.generateElementCode(elem)
		if elementCode != "" {
			code.WriteString(elementCode)
			elementCount++
		}
	}

	code.WriteString("\n\treturn ds\n")
	code.WriteString("}\n")

	if elementCount > 0 {
		fmt.Fprintf(&code, "\n// Total elements: %d\n", elementCount)
	}

	return code.String()
}

// generateElementCode generates Go code for a single element
func (cc *CodifyCommand) generateElementCode(elem DicomElement) string {
	var code strings.Builder

	parts := strings.Split(elem.Tag, ",")
	if len(parts) != 2 {
		return ""
	}

	var group, element uint16
	_, err := fmt.Sscanf(parts[0], "%X", &group)
	if err != nil {
		return ""
	}
	_, err = fmt.Sscanf(parts[1], "%X", &element)
	if err != nil {
		return ""
	}

	t := tag.New(group, element)
	tagName := t.GetName()
	if tagName == "" {
		tagName = fmt.Sprintf("Tag_%04X_%04X", group, element)
	}

	valueCode := cc.formatValue(elem.VR, elem.Value)
	if valueCode == "" {
		return ""
	}

	fmt.Fprintf(&code, "\t// (%s) %s (%s)\n", elem.Tag, tagName, elem.VR)
	code.WriteString("\tds.Add(dataelem.NewDataElement(\n")
	fmt.Fprintf(&code, "\t\ttag.New(0x%04X, 0x%04X),\n", group, element)
	fmt.Fprintf(&code, "\t\tdataelem.%s,\n", elem.VR)
	fmt.Fprintf(&code, "\t\t%s,\n", valueCode)
	code.WriteString("\t))\n\n")

	return code.String()
}

// formatValue formats a value for Go code
func (cc *CodifyCommand) formatValue(vr string, value []byte) string {
	vr = strings.TrimSpace(vr)

	if vr == "OB" || vr == "OW" || vr == "OF" || vr == "OD" || vr == "OL" {
		return fmt.Sprintf("[]byte{/* %d bytes */}", len(value))
	}

	strVal := string(value)
	strVal = strings.TrimRight(strVal, "\x00")

	isPrintable := true
	for _, r := range strVal {
		if r < 32 && r != '\t' && r != '\n' && r != '\r' {
			isPrintable = false
			break
		}
	}

	if !isPrintable {
		return fmt.Sprintf("[]byte{/* %d bytes, non-printable */}", len(value))
	}

	strVal = strings.ReplaceAll(strVal, "\\", "\\\\")
	strVal = strings.ReplaceAll(strVal, "\"", "\\\"")
	strVal = strings.ReplaceAll(strVal, "\n", "\\n")
	strVal = strings.ReplaceAll(strVal, "\r", "\\r")
	strVal = strings.ReplaceAll(strVal, "\t", "\\t")

	return fmt.Sprintf("\"%s\"", strVal)
}

// showHelp displays help information for the codify command.
func (cc *CodifyCommand) showHelp() {
	fmt.Print(`COMMAND: codify - Convert DICOM file to Go code

USAGE:
  go-dicom codify <file> [options]

DESCRIPTION:
  Read a DICOM file and produce Go code that can recreate it. Useful for
  documentation, testing, and sharing DICOM file structures.

OPTIONS:
  -h, --help                Show help for this command
  --exclude-size <N>        Exclude binary data larger than N bytes (default: 100)
  --exclude-private         Exclude private tags (default: true)
  --output <file>           Output file (if not specified, writes to stdout)
  --package <name>          Go package name (default: main)
  --function <name>         Function name (default: createDataset)

EXAMPLES:
  go-dicom codify patient.dcm
  go-dicom codify patient.dcm > create_patient.go
  go-dicom codify patient.dcm --output patient.go --exclude-size 1000
  go-dicom codify patient.dcm --exclude-private=false
  go-dicom codify patient.dcm --package mypackage --function createMyDataset
  go-dicom codify -h
`)
}
